name: Plugin - Bug Report
description: File a plugin bug report
title: "[Plugin Bug]: "
labels: ["plugin", "bug"]
assignees:
  - OlavWolfiken
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: plugin
    attributes:
      label: Which plugin are you having trouble with?
      multiple: false
      options:
        - PLACEHOLDER
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: client
    attributes:
      label: What Discord client are you using the plugin on?
      multiple: true
      options:
        - Stable
        - Canary
        - PTB
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: What is your Discord client's version?
      placeholder: ex. Stable 118205 (081ceba)
    validations:
      required: false
